# 040424, Thursday, 11.00 am 
# Docker Compose version v2.29.1
# Docker version 27.1.1, build 6312585

services: 
  cutetube-api: &api   # anchor of cutetube-api to reuse the cutetube-api content.  
    restart: always 
    build: 
      context: . 
      dockerfile: ./docker/production/django/Dockerfile
    image: cutetube-api-image
    volumes: 
      - production_cutetube_vod_media_files:${APP_HOME}/app/vod-media-files  # APP_HOME: /home/cutetube
      - production_cutetube_static_volume:${APP_HOME}/app/staticfiles
      - production_cutetube_media_volume:${APP_HOME}/app/mediafiles 
    env_file: 
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    depends_on: 
      - postgres
      - cutetube-redis
    command: /start  
    networks: 
      - production-cutetube-backend-api-network

  postgres: 
    build: 
      context: . 
      dockerfile: ./docker/production/postgres/Dockerfile
    image: cutetube-pg-image
    volumes: 
      - production_cutetube_postgres_data:/var/lib/postgresql/data
      - production_cutetube_postgres_data_backups:/backups
    env_file: 
      - ./.envs/.production/.postgres 
    networks: 
      - production-cutetube-backend-api-network

  # TODO use nginx-proxy-manager in Production
  nginx: 
    build: 
      context: . 
      dockerfile: ./docker/production/nginx/Dockerfile
    restart: always
    depends_on: 
      - cutetube-api 
    volumes: 
      - production_cutetube_static_volume:/app/staticfiles
      - production_cutetube_media_volume:/app/mediafiles 
    ports: 
      - "8080:80"
    networks: 
      - production-cutetube-backend-api-network
    
  cutetube-redis: 
    image: redis:7-alpine
    container_name: cutetube-redis-container
    mem_limit: 50m 
    networks: 
      - production-cutetube-backend-api-network

  cutetube-celery-worker:   # using anchor of api service. 
    <<: *api 
    image: cutetube-celery-image
    command: /start-celeryworker
    # mem_limit: 400m # also allocates same amount of swap  | can't use. server has only 1GB RAM and allocating 400MB receives SIGKILL.
    # As inherited from cutetube-api service, everything is available as cutetube-api service in this service 
    #  Using the same external volume as the cutetube-api (djanog app) as celery needs access to the vod data to process 
          
  flower: 
    <<: *api 
    image: cutetube-flower-image
    command: /start-flower
    volumes: 
      - production_cutetube_flower_data:/data
    ports: 
      - "5555:5555"
    
    

# TODO create the network in the server. 
networks: 
  production-cutetube-backend-api-network: 
    external: true 
  

volumes: 
  production_cutetube_static_volume: {}
  production_cutetube_media_volume: {}
  production_cutetube_postgres_data: {}
  production_cutetube_postgres_data_backups: {}
  production_cutetube_flower_data: {}
  production_cutetube_vod_media_files: 
    external: true 

  