# Generated by Django 4.2.9 on 2024-07-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stream_v3", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videometadata",
            name="original_video_title",
            field=models.CharField(
                editable=False,
                max_length=220,
                verbose_name="Original Video Metadata Title",
            ),
        ),
        migrations.AlterField(
            model_name="videometadata",
            name="title",
            field=models.CharField(
                editable=False, max_length=220, verbose_name="Video Title"
            ),
        ),
    ]
